### ISSUE TITLE
sending embed not working in discordjs v13

### ISSUE THREAD

**Issue by Jam-Manbo** [Glitchii/embedbuilder#11]
As discord.js has released v13, we need to send array of embed (ex. `.send({embeds: [embed]})`  - old version `.send(embed)`), which current version of embed builder doesnt support it.

- Visit https://glitchii.github.io/embedbuilder/ 
- Fill out the embed with messages, copy the JSON.
- Send messages with the JSON you have pasted, it would only send contents.

**Comment by Glitchii** [comment]
This embed builder isn't made to work specifically for Discord.js. It's made to work with any language eg. Discord.py, Discord.Net and more. So there's no better way to put it. If all of them use arrays then I'd probably make the JSON have arrays. Although, it should be easy to turn the JSON from the embed builder to work with Discord.js v13. Put the 'embed' key from the JSON in an array for-example:

Let's say `builtEmbed` is a variable holding the JSON from the embed builder, you could do something like this
```js
.send({ embeds: [ builtEmbed.embed ] })
```
