### ISSUE TITLE
Wrong base64 data link

### ISSUE THREAD

**Issue by D3nied** [Glitchii/embedbuilder#15]
I tried to encode base64 url with java and thir website
https://www.base64decode.org/
Problem somtimes your datalinks starts ending with %3D unless i remove the %3D the base64 data is malformed
https://glitchii.github.io/embedbuilder/?data=JTdCJTIyZW1iZWQlMjIlM0ElN0IlN0QlMkMlMjJjb250ZW50JTIyJTNBJTIyVGhpcyUyMGlzJTIwYSUyMHByb2JsZSUyMiU3RA%3D%3D

**Comment by Glitchii** [comment]
%3D is the URL-encoded representation of the equals sign.
Seems this just happens when you click "data data link, in that case I have made an update (265a23250c770171c94a634e3ef3160070514203) with this issue fixed
