### ISSUE TITLE
Indent Display

### ISSUE THREAD

**Issue by Stage4000** [Glitchii/embedbuilder#17]
If you use the '>' indentation on your embed builder with more than one line it disposes of all but the first line.

Example to reproduce:
In a single embed field on your builder type the following.
> test 1
> test 2

Only test 1 will show in the preview.

Tested on Chromium based browser.

**Comment by Glitchii** [comment]
Fix 👍 46dfceb2cc0e97a5e35e45228fb16a11df6f8c28
