### ISSUE TITLE
ReferenceError: hljs is not defined

### ISSUE THREAD

**Issue by QaisZAK** [Glitchii/embedbuilder#3]
**Error:** `ReferenceError: hljs is not defined`
**Found at:** Bottom of the page. Fired by:
```js
error = (msg, time) => {
            notif.innerHTML = msg, notif.style.display = 'block';
            time && setTimeout(() => notif.animate({ opacity: '0', bottom: '-50px', offset: 1 }, { easing: 'ease', duration: 500 })
                .onfinish = () => notif.style.removeProperty('display'), time);
            return false;
        }
```
At lines 96 - 101

---
**Reproduction Steps:**
- Clone repo
- Run index.js

**Comment by Glitchii** [comment]
You're not meant to run the JS file. You are meant to run the HTML file. JS will be loaded from the HTML file with highlightjs
