### ISSUE TITLE
Delete embed properties which are set to "" or empty array

### ISSUE THREAD

**Issue by CayeOficial** [Glitchii/embedbuilder#36]
Discord's api now doesn't support parsing of json embeds with empty properties like this:
`{"embed":{"title":"","description":"Hello! This won't work because title is empty and thumbnail url too!","color":4321431,"thumbnail":{"url":""}}}`

So, I suggest to delete the property instead of letting it be `""` (or empty array in case of fields), because discord doesn't support this now and this only causes problems.
It will look like this: `{"embed":{"description":"Yay! No empty properties, now it works!","color":4321431}}`

Same thing for `content`

**Comment by Glitchii** [comment]
Do you mind elaborating a bit? It seems to work. Except the text that is "" is not eg. the title is not shown by Discord.
This is the same behavior with the embed builder. Perhaps I've miss understood?

Test code:
```py
import requests
import json

webhook_url = ""

requests.post(
    webhook_url,
    headers={ "Content-Type": "application/json" },
    data=json.dumps({
        "embeds": [{
            "title": "",
            "description": "Hello! This won't work because title is empty and thumbnail url too!",
            "color": 4321431,
            "thumbnail": { "url": "" }
        }]
    })
)
```
Discord output:

![image](https://user-images.githubusercontent.com/46096865/211835365-e7ffedbb-8627-4ea6-8f18-d1d695ca9d6c.png)

**Comment by CayeOficial** [comment]
It might work with webhooks, however on discord.js lastest version does not work with the client itself not a webhook

**Comment by Glitchii** [comment]
Added on commit bd9406169248dc93be5354ad807a085e3e632d89
Here is how it works, once you enter a key with an empty valid using the JSON editor, the editor will not be updated so not to interrupt, instead, the file JSON will not have that key.

You can test it by writing an empty key, then print json in console or switch to the GUI tab then back to the JSON editor, the key will not be there.

Also in the commit, the same will happen to keys that are not accepted by discord.
Test it out with this test data
```json
{
    "content": "Lorem ipsum",
    "embeds": [
        {
            "title": "",
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
            "color": 4321431,
            "number": 1234,
            "text": "Hello",
            "emptyObject": {},
            "thumbnail": {
                "url": ""
            },
            "author": {
                "name": "Me",
                "icon_url": "https://cdn.discordapp.com/embed/avatars/0.png",
                "icon": "https://cdn.discordapp.com/embed/avatars/0.png",
                "url": "https://discord.com"
            },
            "test": {
                "test1": {
                    "test2": ""
                }
            },
            "testing": {
                "testing1": {
                    "testing2": "testing3"
                }
            },
            "fields": [
                {
                    "name": "Field name",
                    "value": "Field value",
                    "inline": true
                },
                {
                    "name": "Another Field name",
                    "value": "And another value",
                    "inline": true,
                    "outline": false
                }
            ]
        }
    ]
}
```
