### ISSUE TITLE
?data= parameter breaks utf8

### ISSUE THREAD

**Issue by ColorsCrypt** [Glitchii/embedbuilder#39]
This is my data parameter:
`JTdCJTIyY29udGVudCUyMjolMjIlMjIsJTIyZW1iZWRzJTIyOiU1QiU3QiUyMnRpdGxlJTIyOiUyMioqU3RyZWFrJTIwemVyc3QlQzMlQjZydCEqKiUyMiwlMjJ0eXBlJTIyOiUyMnJpY2glMjIsJTIyZGVzY3JpcHRpb24lMjI6JTIyRGllJTIwJTNDIzg2MDg5MzM4NzY0NTY0ODkwNiUzRSUyMFN0cmVhayUyMHd1cmRlJTIwZ2Vicm9jaGVuOiU1Q25FcndhcnRldGUlMjBaYWhsOiUyMDE0JTVDbklucHV0JTIwdm9uJTIwJTNDQDk4MDQzNzQyOTI1NTMwNzMxNCUzRTolMjAxJTIyLCUyMmNvbG9yJTIyOjE2NzExNjgwLCUyMmZvb3RlciUyMjolN0IlMjJ0ZXh0JTIyOiUyMlNvbGx0ZSUyMGRlciUyMEVpbmRydWNrJTIwZW50c3RlaGVuLCUyMGRhcyUyMGRpZSUyMFN0cmVhayUyMGFic2ljaHRsaWNoJTIwemVyc3QlQzMlQjZydCUyMHd1cmRlJTIwdW5kJTIwZXMlMjBuaWNodCUyMGRhcyUyMGVyc3RlJTIwbWFsJTIwaXN0LCUyMGJpdHRlJTIwZW50c3ByZWNoZW5kZSUyME1hJUMzJTlGbmFobWVuJTIwZXJncmVpZmVuKHouQiUyMEF1c3NjaGx1c3MlMjB2b20lMjBDaGFubmVsKSElMjIlN0QlN0QlNUQlN0Q=`

It was first URLEncoded and then hashed with base64.
When I manually reverse the process, everything works as it should. But when I open the url with the data parameter some characters break(Ü, Ö, ß etc., see below)
![image](https://user-images.githubusercontent.com/126079750/220626783-13f2536d-5924-4de3-926a-4709d18babb6.png)

**Comment by Glitchii** [comment]
- What is the original text.
- How are you encoding and decoding them; are you using the `jsonToBase64` or `base64ToJson` functions or at least a functions that use the same algorithm?

Confirm that you see
```
Asdf

Ü, Ö, ß
```
From this link https://glitchii.github.io/embedbuilder/?data=JTdCJTIyY29udGVudCUyMiUzQSUyMkFzZGYlNUNuJTVDbiVEQyUyQyUyMCVENiUyQyUyMCVERiUyMiU3RA%3D%3D

**Comment by ColorsCrypt** [comment]
The original text is: 
```
'{"content":"","embeds":[{"title":"**Streak zerstört!**","type":"rich","description":"Die <#860893387645648906> Streak wurde gebrochen:\\nErwartete Zahl: 14\\nInput von <@980437429255307314>: 1","color":16711680,"footer":{"text":"Sollte der Eindruck entstehen, das die Streak absichtlich zerstört wurde und es nicht das erste mal ist, bitte entsprechende Maßnahmen ergreifen(z.B Ausschluss vom Channel)!"}}]}'
```

I encode it(Node.js) first with `encodeURI()` and then `Buffer.from(dataURL).toString('base64')` and the result is this:
```
JTdCJTIyY29udGVudCUyMjolMjIlMjIsJTIyZW1iZWRzJTIyOiU1QiU3QiUyMnRpdGxlJTIyOiUyMioqU3RyZWFrJTIwemVyc3QlQzMlQjZydCEqKiUyMiwlMjJ0eXBlJTIyOiUyMnJpY2glMjIsJTIyZGVzY3JpcHRpb24lMjI6JTIyRGllJTIwJTNDIzg2MDg5MzM4NzY0NTY0ODkwNiUzRSUyMFN0cmVhayUyMHd1cmRlJTIwZ2Vicm9jaGVuOiU1Q25FcndhcnRldGUlMjBaYWhsOiUyMDE0JTVDbklucHV0JTIwdm9uJTIwJTNDQDk4MDQzNzQyOTI1NTMwNzMxNCUzRTolMjAxJTIyLCUyMmNvbG9yJTIyOjE2NzExNjgwLCUyMmZvb3RlciUyMjolN0IlMjJ0ZXh0JTIyOiUyMlNvbGx0ZSUyMGRlciUyMEVpbmRydWNrJTIwZW50c3RlaGVuLCUyMGRhcyUyMGRpZSUyMFN0cmVhayUyMGFic2ljaHRsaWNoJTIwemVyc3QlQzMlQjZydCUyMHd1cmRlJTIwdW5kJTIwZXMlMjBuaWNodCUyMGRhcyUyMGVyc3RlJTIwbWFsJTIwaXN0LCUyMGJpdHRlJTIwZW50c3ByZWNoZW5kZSUyME1hJUMzJTlGbmFobWVuJTIwZXJncmVpZmVuKHouQiUyMEF1c3NjaGx1c3MlMjB2b20lMjBDaGFubmVsKSElMjIlN0QlN0QlNUQlN0Q=
```

And for decoding(tested in in browser to check if it works in js). First i call `atob()` with the base64 string to get the URLEncoded string and then `decodeURI()` to get the string json.

And when I click the link everything works as it should and I see:
```
Asdf

Ü, Ö, ß
```

**Comment by Glitchii** [comment]
Maybe use `encodeURIComponent()` instead of `encodeURI()`. They work closely the same but `encodeURIComponent()` works best with special characters. Let me know if this helps
