### ISSUE TITLE
Preview Issue

### ISSUE THREAD

**Issue by Walkaisa** [Glitchii/embedbuilder#43]
If you don't provide any `guiTabs` in the `builder.config.js`, the preview of the embed is broken. If you add in the `assets/js/script.js` on line `962` a `if` statement if there are any values inside the tabs array, you can prevent this.

E.g:
```js
if (tabs.length) {
    for (const e of document.querySelectorAll(\`.${tabs.join(', .')}\`))  e.classList.add('active');
}

**Comment by Glitchii** [comment]
Should now be fixed after commit f37e9bc8a0655b2a2bb3dc7dbd3d65d8d5d4f209
