### ISSUE TITLE
Footer icon not updated after uploading image from local device

### ISSUE THREAD

**Issue by HexM7** [Glitchii/embedbuilder#9]
The footer icon is not getting updated when an image is successfully uploaded from the device.
Steps to reproduce:
- Visit https://glitchii.github.io/embedbuilder/
- Upload footer icon from device
- Footer icon does not update on its own, neither I can see its URL in JSON tab.

**Comment by Glitchii** [comment]
Fixed https://github.com/Glitchii/embedbuilder/commit/4f298019256f096ba4aba1f3e1ca534ad9103615

**Comment by HexM7** [comment]
Maybe the `maxlength` attribute for author name is accidentally removed in this commit. (`script.js, line 189`)

**Comment by Glitchii** [comment]
I've added it back. Thought I pulled after making that change.
